name: Backtest-Cpp CI

on:
  push:
    branches:
      - main
      - 'v*'
  pull_request:
    branches:
      - main
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.22.1'

      - name: Build and test
        run: |
          mkdir build
          cd build
          cmake ..
          make -j4
          cd Examples/SupportResistance
          ./SupportResistance
